language: node_js
node_js:
  - "0.12"
  - "4.1"
env:
  global:
    - COVERALLS_REPO_TOKEN=30zWLgtRYNYsmlsogIALMzJ60hVFDeCM8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - npm run coverall
